### PR TITLE
Add Hexalem project

### PR DESCRIPTION
**Pull request by RostislavLitovkin**

### CODE REVIEW

**Comment by juniuszhou** [comment]
Don't update .gitignore, don't add files in docs. please move all into your project's folder.

**Comment by Apolixit** [comment]
Hello :)
What do we need to do to get our PR merged ? 👍

**Comment by Apolixit** [comment]
@juniuszhou can we merge the PR ? :)

**Comment by darkfriend77** [comment]
@juniuszhou The PR should be fine to merge, Is anything left to change?

**Pull request merged**
