### PR TITLE
Added Polka Finance & Polka Social Project

### PR DESCRIPTION
**Pull request by ShivamAgarwal-code**
Added the project for Polkadot WInter 2023 Hackathon

### CODE REVIEW

**Comment by ShivamAgarwal-code** [comment]
Track: Substrate Pallets

**Comment by juniuszhou** [comment]
The PR should be submitted before Dec 22.

**Comment by juniuszhou** [comment]
https://dorahacks.io/hackathon/polkadot-hackathon-2023-winter/detail

**Comment by ShivamAgarwal-code** [comment]
@juniuszhou Yes I know that actually I was having some queries and I dm'ed Tracy but she was not replying so it got late to submit the PR, though I submitted my project in dorahacks within the deadline so kindly consider my project, hope you will understand...

**Pull request merged**
